### ISSUE TITLE
Assertion error `assertion failed: self.is_leaf()` when deserialising `BTreeSet<u8>`

### ISSUE THREAD

**Issue by 5225225** [rkyv/rkyv#302]
```rust
use std::collections::BTreeSet;

fn main() {
    let data = [
        0, 0, 0, 0, 253, 6, 239, 6, 255, 255, 255, 252, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 5, 0, 0,
        0, 0, 240, 255, 255, 255, 1, 128, 0, 249, 220, 255, 255, 255, 4, 0, 0, 96, 0, 0, 0, 249,
        232, 255, 255, 255,
    ];

    rkyv::from_bytes::<BTreeSet<u8>>(&data);
}
```

```rust
thread 'main' panicked at 'assertion failed: self.is_leaf()', /home/jess/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/874f684/rkyv/src/collections/btree_map/mod.rs:181:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/060e47f74a91b28c3db28d80a6a9d6841ca51026/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/060e47f74a91b28c3db28d80a6a9d6841ca51026/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/060e47f74a91b28c3db28d80a6a9d6841ca51026/library/core/src/panicking.rs:48:5
   3: rkyv::collections::btree_map::NodeHeader::classify_leaf
             at /home/jess/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/874f684/rkyv/src/collections/btree_map/mod.rs:181:9
   4: rkyv::collections::btree_map::validation::_::<impl bytecheck::CheckBytes<C> for rkyv::collections::btree_map::ArchivedBTreeMap<K,V>>::check_bytes
             at /home/jess/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/874f684/rkyv/src/collections/btree_map/validation.rs:579:41
   5: rkyv::collections::btree_set::_::<impl bytecheck::CheckBytes<__C> for rkyv::collections::btree_set::ArchivedBTreeSet<K>>::check_bytes
             at /home/jess/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/874f684/rkyv/src/collections/btree_set.rs:11:32
   6: rkyv::validation::internal_check_archived_value_with_context
             at /home/jess/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/874f684/rkyv/src/validation/mod.rs:324:13
   7: rkyv::validation::check_archived_root_with_context
             at /home/jess/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/874f684/rkyv/src/validation/mod.rs:364:5
   8: rkyv::validation::validators::check_archived_root
             at /home/jess/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/874f684/rkyv/src/validation/validators/mod.rs:228:5
   9: rkyv::validation::validators::util::from_bytes
             at /home/jess/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/874f684/rkyv/src/validation/validators/util.rs:70:5
  10: scratch5ubHkOF8N::main
             at ./main.rs:10:5
  11: core::ops::function::FnOnce::call_once
             at /rustc/060e47f74a91b28c3db28d80a6a9d6841ca51026/library/core/src/ops/function.rs:248:5
```

**Comment by djkoloski** [comment]
Fixed by 7f9b96ceb09c01998a37e15ff989bb4ec7712da4
