### ISSUE TITLE
Huge memory consumption for large archive (17Gb+)

### ISSUE THREAD

**Issue by XavDesbordes** [rkyv/rkyv#489]
Hi,
I tried to gather multiple sources of rkyv archives with this schema:
The ram usage for the object gathering these different archives was circa 17Gb. This may be an important point.

```
#[derive(Default, Archive, Serialize, Deserialize)]

pub(crate) struct Sum {
        pub(crate) value: Vec<u64>
}

#[derive(Default, Archive, Serialize, Deserialize)]

pub(crate) struct SumsObject {
        pub(crate) vec: Vec<Sum>
}
```

Each archive was 1.1Gb and I created an object in memory that gathered them.
Fine.

It was going well up to the call to serialization:
```
let ser = rkyv::to_bytes::<
                                SumsObject,
                                {

                                        (1_u32 << 28) as usize
                                }
                        >(&sums_object_out)
                        .unwrap();
```

From there, the ram usage went through the top.
I have a 256Gb ram machine and it exhausted it in a matter of seconds.

Tried with different options as well in the cargo file, like:
```
rkyv = { version = "0.7.43", default-features = false, features = [
        "validation",
        "copy",
        "bytecheck",
        "std",
        "copy_unsafe",
        "size_64",

] }
```
Without any luck. Maybe I forgot to modify something else in my code to use that.

What was going on ?
Thanks,

**Comment by djkoloski** [comment]
1. I don't think that rkyv should be using that much auxiliary memory.
2. Most of the memory usage should be for the output buffer since you have a large amount of data.
3. When writing very large archives, you probably want to stream directly to disk instead of buffering in an intermediate byte vector. You can do this using [`WriteSerializer`](https://docs.rs/rkyv/latest/rkyv/ser/serializers/struct.WriteSerializer.html).

Unfortunately I can't directly help much without more details. A reproducer would be best.

**Comment by XavDesbordes** [comment]
Ok, you want the full code for the gathering function ? 
There you go:

```
#[derive(Default, Archive, Serialize, Deserialize)]

pub(crate) struct Sum {
        pub(crate) value: Vec<u64>
}

#[derive(Default, Archive, Serialize, Deserialize)]

pub(crate) struct SumsObject {
        pub(crate) vec: Vec<Sum>
}


pub(crate) fn gather_sums_vec() {

        // --------------------------------------------------------------------------
        // Must be launched on the same machine as the one doing the function above
        // --------------------------------------------------------------------------
        let cores = 12;

        let mut sums_object_out = SumsObject {
                vec: vec![]
        };

        {

                let mut vec_archives: Vec<(*mut u8, &ArchivedSumsObject, u32)> = vec![];

                for core_id in 0..cores {

                        let str_now = "path_with_core_as_suffix";

                        println!("{}", str_now);

                        let new_file = File::open(str_now).unwrap();

                        let len = new_file.metadata().unwrap().len();

                        let ptr: *mut u8;

                        let addr = unsafe {

                                ptr = libc::mmap(ptr::null_mut(), len as usize, libc::PROT_READ, libc::MAP_PRIVATE, new_file.as_raw_fd(), 0) as *mut u8;

                                &*slice_from_raw_parts(ptr, len as usize)
                        };

                        let archive = unsafe {

                                rkyv::archived_root::<SumsObject>(addr)
                        };

                        vec_archives.push((ptr, archive, len as u32));
                }

                // -----------
                // Now merge
                // -----------
                let mut cursor: usize = 0;

                let mut modified = true;

                let max_cursor = vec_archives[0].1.vec.len();

                loop {

                        println!("Cursor {} / {}", cursor, max_cursor);

                        for arch in vec_archives.iter() {

                                if arch.1.vec.len() > cursor {

                                        let element: Sum = arch.1.vec[cursor]
                                                .deserialize(&mut rkyv::Infallible)
                                                .unwrap();

                                        sums_object_out.vec.push(element);

                                        modified = true;
                                }
                        }

                        if !modified {

                                break;
                        }

                        cursor += 1;

                        modified = false;
                }
        }       

        // -----------
        // Serialize
        // -----------
        let ser = rkyv::to_bytes::<
                SumsObject,
                {

                        (1_u32 << 28) as usize
                }
        >(&sums_object_out)
        .unwrap();

        let mut file_out = File::create("path_out").unwrap();

        let _ = file_out.write_all(ser.as_slice());
}

```
I can't give you the archives to gather because of the sensitive data inside.
The object contains the proper data.

Thanks

**Comment by XavDesbordes** [comment]
Tried the write serializer but I lose my schema `SumsObject` doing so
```
  use rkyv::ser::{
          serializers::WriteSerializer,
          Serializer
  };

  let f = File::create("out_file.txt").unwrap();

  let mut serializer = WriteSerializer::new(&f);

  assert_eq!(serializer.pos(), 0);

  let _ = serializer.write(&[0u8, 1u8, 2u8, 3u8]);

  assert_eq!(serializer.pos(), 4);
```
The doc didn't help to make my way through it..

**Comment by XavDesbordes** [comment]
Tried to reduce the size of the gathered archives to 2 instead of 12, and this is what I got:

```
thread 'Preparation::test::t4' panicked at user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/rel_ptr/mod.rs:300:42:
called `Result::unwrap()` on an `Err` value: ExceedsStorageRange
stack backtrace:
   0: rust_begin_unwind
             at /rustc/766bdce744d531267d53ba2a3f9ffcda69fb9b17/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/766bdce744d531267d53ba2a3f9ffcda69fb9b17/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/766bdce744d531267d53ba2a3f9ffcda69fb9b17/library/core/src/result.rs:1654:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/766bdce744d531267d53ba2a3f9ffcda69fb9b17/library/core/src/result.rs:1077:23
   4: rkyv::rel_ptr::RelPtr<T,O>::emplace
             at user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/rel_ptr/mod.rs:300:9
   5: rkyv::vec::ArchivedVec<T>::resolve_from_len
             at user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/vec/mod.rs:99:9
   6: rkyv::vec::ArchivedVec<T>::resolve_from_slice
             at user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/vec/mod.rs:87:9
   7: rkyv::impls::alloc::vec::<impl rkyv::Archive for alloc::vec::Vec<T>>::resolve
             at user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/impls/alloc/vec.rs:46:9
   8: MyApp::_::<impl rkyv::Archive for MyApp::Sum>::resolve
             at ./src/compress/compressor_main_rug.rs:33:27
   9: <rkyv::ser::serializers::alloc::AlignedSerializer<A> as rkyv::ser::Serializer>::resolve_aligned
             at user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/ser/serializers/alloc.rs:84:9
  10: <rkyv::ser::serializers::CompositeSerializer<S,C,H> as rkyv::ser::Serializer>::resolve_aligned
             at user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/ser/serializers/mod.rs:161:9
  11: rkyv::impls::core::<impl rkyv::SerializeUnsized<S> for [T]>::serialize_unsized
             at user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/impls/core/mod.rs:216:21
  12: rkyv::vec::ArchivedVec<T>::serialize_from_slice
             at user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/vec/mod.rs:116:18
  13: rkyv::impls::alloc::vec::<impl rkyv::Serialize<S> for alloc::vec::Vec<T>>::serialize
             at user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/impls/alloc/vec.rs:53:9
  14: MyApp::_::<impl rkyv::Serialize<__S> for MyApp::SumsObject>::serialize
             at ./src/compress/compressor_main_rug.rs:39:36
  15: rkyv::ser::Serializer::serialize_value
             at user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/ser/mod.rs:78:24
  16: rkyv::util::to_bytes
             at user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/util/mod.rs:294:5
  17: MyApp::Preparation::gather_sums_vec
             at ./src/compress/compressor_main_rug.rs:1385:35
  18: MyApp::Preparation::test::t4
             at ./src/compress/compressor_main_rug.rs:1501:33
  19: MyApp::Preparation::test::t4::{{closure}}
             at ./src/compress/compressor_main_rug.rs:1499:32
  20: core::ops::function::FnOnce::call_once
             at /rustc/766bdce744d531267d53ba2a3f9ffcda69fb9b17/library/core/src/ops/function.rs:250:5
  21: core::ops::function::FnOnce::call_once
             at /rustc/766bdce744d531267d53ba2a3f9ffcda69fb9b17/library/core/src/ops/function.rs:250:5
```

I still had plenty of ram/disk left. I don't understand.

**Comment by XavDesbordes** [comment]
Apparently, it is a rust issue with metadata handling.
Well, I guess I am out of luck on this one, and i will use a simple `mmap` instead.

Please correct me/my code if I am wrong, as a serialized data is much more comfortable to work with.

**Comment by djkoloski** [comment]
Based on `rkyv::rel_ptr::RelPtr<T,O>::emplace` being in the backtrace, it looks like the crash you encountered is because rkyv uses 32-bit relative pointers by default. This means that it trades off a smaller pointer size for a maximum file size of 4GB. You can enable the `size_64` feature to switch rkyv to 64-bit relative pointers, which will increase the file size limit to ~9EB.

**Comment by XavDesbordes** [comment]
Switching to size_64 caused a crash at the deserialization step. Maybe because it has not been serialized with size_64 in the first place. So, I had to make it run using `mmap` and an index.
Next time, I will consider using `size_64` all along. Stupid me.
