### ISSUE TITLE
Serialization and deserialization, reflexivity issues

### ISSUE THREAD

**Issue by GengYage** [rkyv/rkyv#490]
Hello, I am a newbie in rkyv. I found a problem when verifying the reflexivity of serialization and deserialization. The following is the source code:

```rust
use std::collections::HashMap;

fn main() {
    use rkyv::{Archive, Deserialize, Serialize};

    #[derive(Archive, Deserialize, Serialize, Debug, PartialEq)]
    #[archive(check_bytes)]
    #[archive_attr(derive(Debug))]
    struct Test {
        int: u8,
        string: String,
        option: Option<Vec<i32>>,
        map: HashMap<TestEnum, String>,
    }

    #[derive(Archive, Deserialize, Serialize, Debug, PartialEq, Eq, Hash)]
    #[archive(check_bytes)]
    #[archive_attr(derive(Debug, PartialEq, Eq, Hash))]
    enum TestEnum {
        A(u8),
        B,
    }

    let mut map = HashMap::new();
    map.insert(TestEnum::B, "hello".to_string());
    map.insert(TestEnum::A(1), "world".to_string());
    let value = Test {
        int: 42,
        string: "hello world".to_string(),
        option: Some(vec![1, 2, 3, 4]),
        map,
    };

    use rkyv::ser::{serializers::AllocSerializer, Serializer};

    let mut serializer = AllocSerializer::<0>::default();
    serializer.serialize_value(&value).unwrap();
    let bytes = serializer.into_serializer().into_inner();

    // Error 
    let archived = rkyv::check_archived_root::<Test>(&bytes[..]).unwrap();

    // And you can always deserialize back to the original type
    let deserialized: Test = archived.deserialize(&mut rkyv::Infallible).unwrap();

    println!("{:?}", deserialized);
}
```
and i got an error:
```txt
thread 'main' panicked at src/main.rs:41:66:
called `Result::unwrap()` on an `Err` value: CheckBytesError(StructCheckError { field_name: "map", inner: InvalidKeyPosition { index: 0 } })
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1684a753dbca5d23b2e03568e6fbbb48eb72d0e6/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/1684a753dbca5d23b2e03568e6fbbb48eb72d0e6/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/1684a753dbca5d23b2e03568e6fbbb48eb72d0e6/library/core/src/result.rs:1654:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/1684a753dbca5d23b2e03568e6fbbb48eb72d0e6/library/core/src/result.rs:1077:23
   4: rkyv_exp::main
             at ./src/main.rs:41:20
   5: core::ops::function::FnOnce::call_once
             at /rustc/1684a753dbca5d23b2e03568e6fbbb48eb72d0e6/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Can anyone help me?

**Comment by djkoloski** [comment]
I reproduced this issue and confirmed that it's a case of #287. Adding `#[repr(u8)]` to `TestEnum` fixed it for me.
