### ISSUE TITLE
Reproducible allocator memory fault in serialization to_bytes()

### ISSUE THREAD

**Issue by xangelix** [rkyv/rkyv#517]
(Main Branch)

The following code appears to reliably trigger an overflow with the following backtrace. In release mode this causes a memory fault.

Not exactly sure what is going on here, but hopefully this is helpful!

<details>

<summary>Code</summary>

```rs
fn main() {
    let reader = std::io::Cursor::new(DATA);
    let tables: Vec<Table> = ron::de::from_reader(reader).unwrap();

    let bytes = rkyv::to_bytes::<rkyv::rancor::Error>(&tables).unwrap();
    println!("Bytes: {:?}", bytes.len());
}

#[derive(
    serde::Serialize, serde::Deserialize, rkyv::Archive, rkyv::Serialize, rkyv::Deserialize,
)]
pub struct Table(String, Vec<Rows>);

#[derive(
    serde::Serialize, serde::Deserialize, rkyv::Archive, rkyv::Serialize, rkyv::Deserialize,
)]
pub struct Rows(Vec<Row>);

#[derive(
    serde::Serialize, serde::Deserialize, rkyv::Archive, rkyv::Serialize, rkyv::Deserialize,
)]
pub struct Row(Vec<String>);

const DATA: &str = r#"
[
    ("", [
        ([
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
        ]),
    ]),
    ("", [
        ([
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
            ([]),
        ]),
    ]),
]
"#;
```

</details>

<details>

<summary>Backtrace</summary>

```
thread 'main' panicked at /home/tux/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/9462325/rkyv/src/ser/allocator/alloc.rs:257:21:
attempt to subtract with overflow
stack backtrace:
   0:     0x5f84cbf9fad5 - std::backtrace_rs::backtrace::libunwind::trace::h58eed11393533053
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x5f84cbf9fad5 - std::backtrace_rs::backtrace::trace_unsynchronized::h6af9bae28ebb6388
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5f84cbf9fad5 - std::sys_common::backtrace::_print_fmt::hb6748916642a4fb2
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x5f84cbf9fad5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3692694645b1bb6a
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5f84cbfbdceb - core::fmt::rt::Argument::fmt::h7aa93977ba74ae0f
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/fmt/rt.rs:165:63
   5:     0x5f84cbfbdceb - core::fmt::write::h5131d80b4c69b88d
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/fmt/mod.rs:1168:21
   6:     0x5f84cbf9d8ef - std::io::Write::write_fmt::h1fb327a7d8b0eb36
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/io/mod.rs:1835:15
   7:     0x5f84cbf9f8ae - std::sys_common::backtrace::_print::he6ebb7b9d89f4456
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5f84cbf9f8ae - std::sys_common::backtrace::print::h998d75b840f75a73
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5f84cbfa0c49 - std::panicking::default_hook::{{closure}}::h18ec7fe6a38b9da0
  10:     0x5f84cbfa09ea - std::panicking::default_hook::hfb3f22c2e4075a6a
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:298:9
  11:     0x5f84cbfa1103 - std::panicking::rust_panic_with_hook::h51af00bcb4660c4e
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:795:13
  12:     0x5f84cbfa0fab - std::panicking::begin_panic_handler::{{closure}}::h39f76aa863fbe8ce
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:656:13
  13:     0x5f84cbf9ff99 - std::sys_common::backtrace::__rust_end_short_backtrace::h4d10fc2251b89840
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x5f84cbfa0d17 - rust_begin_unwind
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:652:5
  15:     0x5f84cbfbce83 - core::panicking::panic_fmt::h319840fcbcd912ef
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panicking.rs:72:14
  16:     0x5f84cbfc1387 - core::panicking::panic_const::panic_const_sub_overflow::h3ac2048727405c68
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panicking.rs:179:21
  17:     0x5f84cbf6f550 - <rkyv::ser::allocator::alloc::ArenaHandle as rkyv::ser::allocator::Allocator<E>>::pop_alloc::h04fc71d47cb0fd6e
                               at /home/tux/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/9462325/rkyv/src/ser/allocator/alloc.rs:257:21
  18:     0x5f84cbf79c31 - <rkyv::ser::Serializer<W,A,S> as rkyv::ser::allocator::Allocator<E>>::pop_alloc::h20f074ef17d955e9
                               at /home/tux/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/9462325/rkyv/src/ser/mod.rs:83:18
  19:     0x5f84cbf7c46d - <rancor::Strategy<T,E> as rkyv::ser::allocator::Allocator<E>>::pop_alloc::hc6673c9991c9fa61
                               at /home/tux/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/9462325/rkyv/src/ser/allocator/mod.rs:61:18
  20:     0x5f84cbf78208 - rkyv::util::ser_vec::SerVec<T>::with_capacity::h4091fe15f5012833
                               at /home/tux/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/9462325/rkyv/src/util/ser_vec.rs:62:17
  21:     0x5f84cbf75bc2 - rkyv::impls::core::<impl rkyv::traits::SerializeUnsized<S> for [T]>::serialize_unsized::h5fd62b4b417f7c58
                               at /home/tux/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/9462325/rkyv/src/impls/core/mod.rs:290:13
  22:     0x5f84cbf7f948 - rkyv::vec::ArchivedVec<T>::serialize_from_slice::h92e8dc66f5d77ccf
                               at /home/tux/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/9462325/rkyv/src/vec.rs:115:18
  23:     0x5f84cbf7eafd - rkyv::impls::alloc::vec::<impl rkyv::traits::Serialize<S> for alloc::vec::Vec<T>>::serialize::hb0ff47bc5c707034
                               at /home/tux/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/9462325/rkyv/src/impls/alloc/vec.rs:31:9
  24:     0x5f84cbf76915 - <rkyv_bug::Table as rkyv::traits::Serialize<__S>>::serialize::he4e5966bca47163a
                               at /home/tux/Documents/TensorGuard/app/crates/tg_extractor/src/bin/rkyv_bug.rs:10:58
  25:     0x5f84cbf70805 - rkyv::impls::core::<impl rkyv::traits::SerializeUnsized<S> for [T]>::serialize_unsized::{{closure}}::h2986c6176d03fb74
                               at /home/tux/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/9462325/rkyv/src/impls/core/mod.rs:297:49
  26:     0x5f84cbf78534 - rkyv::util::ser_vec::SerVec<T>::with_capacity::h4783d4757a2b8b45
                               at /home/tux/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/9462325/rkyv/src/util/ser_vec.rs:56:22
  27:     0x5f84cbf75ed2 - rkyv::impls::core::<impl rkyv::traits::SerializeUnsized<S> for [T]>::serialize_unsized::h75adc9fa4c745a68
                               at /home/tux/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/9462325/rkyv/src/impls/core/mod.rs:290:13
  28:     0x5f84cbf7f898 - rkyv::vec::ArchivedVec<T>::serialize_from_slice::h87fb5b51018352c2
                               at /home/tux/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/9462325/rkyv/src/vec.rs:115:18
  29:     0x5f84cbf7e9ad - rkyv::impls::alloc::vec::<impl rkyv::traits::Serialize<S> for alloc::vec::Vec<T>>::serialize::h004f9475acfb5895
                               at /home/tux/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/9462325/rkyv/src/impls/alloc/vec.rs:31:9
  30:     0x5f84cbf7e516 - rkyv::impls::core::<impl rkyv::traits::SerializeUnsized<S> for T>::serialize_unsized::h37b1b64d46dd1be8
                               at /home/tux/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/9462325/rkyv/src/impls/core/mod.rs:75:24
  31:     0x5f84cbf6f8b0 - rkyv::util::serialize::heb4fc664a79106ae
                               at /home/tux/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/9462325/rkyv/src/util/mod.rs:186:5
  32:     0x5f84cbf6f8b0 - rkyv::util::serialize_into::h029fb58d00cd8fae
                               at /home/tux/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/9462325/rkyv/src/util/mod.rs:174:5
  33:     0x5f84cbf64f2c - rkyv::util::alloc::to_bytes_in::{{closure}}::he1da91ed7e33293f
                               at /home/tux/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/9462325/rkyv/src/util/alloc/mod.rs:163:12
  34:     0x5f84cbf6e2e9 - rkyv::util::alloc::arena::with_arena::{{closure}}::h2e8a6cd20417224b
                               at /home/tux/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/9462325/rkyv/src/util/alloc/mod.rs:31:26
  35:     0x5f84cbf64cb8 - std::thread::local::LocalKey<T>::try_with::hdd2235c84eebad17
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/thread/local.rs:283:12
  36:     0x5f84cbf6e182 - std::thread::local::LocalKey<T>::with::ha6037e70c209fe3d
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/thread/local.rs:260:9
  37:     0x5f84cbf6e182 - rkyv::util::alloc::arena::with_arena::h2220f42e93cd8ea6
                               at /home/tux/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/9462325/rkyv/src/util/alloc/mod.rs:28:22
  38:     0x5f84cbf650eb - rkyv::util::alloc::with_arena::h21daa4c9e9a16035
                               at /home/tux/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/9462325/rkyv/src/util/alloc/mod.rs:111:5
  39:     0x5f84cbf650eb - rkyv::util::alloc::to_bytes_in::hb65acba083248dfb
                               at /home/tux/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/9462325/rkyv/src/util/alloc/mod.rs:162:5
  40:     0x5f84cbf650eb - rkyv::util::alloc::to_bytes::h7234342d878328fe
                               at /home/tux/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/9462325/rkyv/src/util/alloc/mod.rs:150:5
  41:     0x5f84cbf7a83d - rkyv_bug::main::hb1575dfa9818cad6
                               at /home/tux/Documents/TensorGuard/app/crates/tg_extractor/src/bin/rkyv_bug.rs:5:17
  42:     0x5f84cbf723cb - core::ops::function::FnOnce::call_once::h890461e92961bd8f
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/ops/function.rs:250:5
  43:     0x5f84cbf7425e - std::sys_common::backtrace::__rust_begin_short_backtrace::h661f4dac86428075
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/sys_common/backtrace.rs:155:18
  44:     0x5f84cbf64d81 - std::rt::lang_start::{{closure}}::h9e42dc3544503dc2
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/rt.rs:159:18
  45:     0x5f84cbf9b2cd - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb84c63630a35bb05
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/ops/function.rs:284:13
  46:     0x5f84cbf9b2cd - std::panicking::try::do_call::h8d62108d97b3e028
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:559:40
  47:     0x5f84cbf9b2cd - std::panicking::try::h0c0b9a214b9691f1
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:523:19
  48:     0x5f84cbf9b2cd - std::panic::catch_unwind::ha8912f28da143edb
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panic.rs:149:14
  49:     0x5f84cbf9b2cd - std::rt::lang_start_internal::{{closure}}::h2baf77487fc7f90d
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/rt.rs:141:48
  50:     0x5f84cbf9b2cd - std::panicking::try::do_call::h36fdc82521d3343f
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:559:40
  51:     0x5f84cbf9b2cd - std::panicking::try::h58aa1415c41e30ec
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:523:19
  52:     0x5f84cbf9b2cd - std::panic::catch_unwind::h3c4b5a8c3b1c4acf
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panic.rs:149:14
  53:     0x5f84cbf9b2cd - std::rt::lang_start_internal::h63a185b0ddd212e9
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/rt.rs:141:20
  54:     0x5f84cbf64d5a - std::rt::lang_start::h34210022e61be95f
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/rt.rs:158:17
  55:     0x5f84cbf7ac4e - main
  56:     0x7c47c20261ce - __libc_start_call_main
                               at /usr/src/debug/glibc/glibc/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  57:     0x7c47c202628a - __libc_start_main_impl
                               at /usr/src/debug/glibc/glibc/csu/../csu/libc-start.c:360:3
  58:     0x5f84cbf63415 - _start
  59:                0x0 - <unknown>

```

</details>

<details>

<summary>Versions</summary>

`rustc 1.80.0 (051478957 2024-07-21)`

```toml
[[package]]
name = "rkyv"
version = "0.8.0-alpha.2"
source = "git+https://github.com/rkyv/rkyv.git#94623252cfb186d177edb07429b9f6759ac3622d"
dependencies = [
 "bitvec",
 "bytecheck",
 "bytes",
 "hashbrown 0.14.5",
 "indexmap",
 "munge",
 "ptr_meta",
 "rancor",
 "rend",
 "rkyv_derive",
 "tinyvec",
 "uuid",
]

[[package]]
name = "rkyv_derive"
version = "0.8.0-alpha.2"
source = "git+https://github.com/rkyv/rkyv.git#94623252cfb186d177edb07429b9f6759ac3622d"
dependencies = [
 "proc-macro2",
 "quote",
 "syn 2.0.72",
]

[[package]]
name = "bytecheck"
version = "0.8.0-alpha.9"
source = "git+https://github.com/rkyv/bytecheck.git#f5dcf094ad6befc9605080631fac7e0abb88ea68"
dependencies = [
 "bytecheck_derive",
 "ptr_meta",
 "rancor",
 "simdutf8",
]

[[package]]
name = "bytecheck_derive"
version = "0.8.0-alpha.9"
source = "git+https://github.com/rkyv/bytecheck.git#f5dcf094ad6befc9605080631fac7e0abb88ea68"
dependencies = [
 "proc-macro2",
 "quote",
 "syn 2.0.72",
]

[[package]]
name = "rancor"
version = "0.1.0-alpha.9"
source = "git+https://github.com/rkyv/rancor.git#3b5406673867cba2525ac61a3e6eee25bacda96d"
dependencies = [
 "ptr_meta",
]
```

</details>

**Comment by djkoloski** [comment]
Thanks for the detailed report! This was due to some errant logic in `Arena` popping, which has been fixed by 971a67ac447ddeb0ce8c151bd416532ae6092a04.
